### ISSUE TITLE
the trait `From<ErrReport>` is not implemented for `ConfigError`

### ISSUE THREAD

**Issue by domenkozar** [moonrepo/schematic#103]
This is useful when showing parsing errors to the user :)

**Comment by milesj** [comment]
@domenkozar I'll be honest, I'm not sure what `ErrReport` is. 

We currently do show parsing errors via miette. Is that not working for you?

**Comment by domenkozar** [comment]
It happens when I call `loader.load().into_diagnostic().wrap_err("...")`, seems to come from here: https://github.com/zkat/miette/blob/22b29eec387d9f96dcbf165ab1b34011868315a9/src/eyreish/mod.rs#L16

**Comment by domenkozar** [comment]
Maybe I'm using the API wrong, how should I show the parsing error?

**Comment by milesj** [comment]
@domenkozar It's built around miette, so you would need to setup miette. https://crates.io/crates/miette#-in-main

I haven't really looked into supporting non-miette use cases yet.

**Comment by domenkozar** [comment]
I was missing at the bottom of https://github.com/zkat/miette?tab=readme-ov-file#-in-main how to do this :)
