### ISSUE TITLE
[feature] Consider using "Parse, don't validate" approach

### ISSUE THREAD

**Issue by 0x009922** [moonrepo/schematic#27]
### The problem

You can specify validation rules, so that `AppConfig` _should_ never be constructed if that validation fails.

```rs
#[derive(Config)]
struct AppConfig {
    #[setting(validate = schematic::validate::alphanumeric)]
    secret_key: String,

    #[setting(validate = schematic::validate::regex("^\.env"))]
    env_file: String,
}
```

It's cool, but the bad thing is that validation is not expressed through type system. I mean, `secret_key: String` doesn't express that it is an alphanumeric.

### A solution I would like

However, you might introduce an `AlphaNumeric` type that can only be constructed after validation (let's imagine `schematic` has `Parse` trait and `ParseError` struct):

```rs
struct AlphaNumeric(String);

impl schematic::Parse for AlphaNumeric {
  fn parse(value: String) -> Result<Self, schematic::ParseError> {
    // validate that `value` is alphanumeric, return `Ok(Self(value))` then
  }
}

#[derive(Config)]
struct AppConfig {
    #[setting(parse)]
    secret_key: AlphaNumeric,

    #[setting(validate = schematic::validate::regex("^\.env"))]
    env_file: String,
}
```

This is just an example. I believe you can find a better way to provide a convenient API for library users.

### Why is it cool

It is a more robust, safe and _idiomatic_ ("[Using the Newtype Pattern for Type Safety and Abstraction](https://doc.rust-lang.org/book/ch19-04-advanced-types.html#using-the-newtype-pattern-for-type-safety-and-abstraction)" in Rust Book, ["Use Strong Types"](https://cheats.rs/#idiomatic-rust)) approach to deal with validation.

Please read the full article: [Parse, don’t validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/)

**Comment by milesj** [comment]
@0x009922 Wouldn't this just fall under serde? `AlphaNumeric` should simply define it's own deserializer.
