### ISSUE TITLE
Merge data from multiple sources

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#29]
Using figment, I could do:

```rs
    Figment::new()
        .merge(Serialized::defaults(AppConfig::default()))
        .merge(Json::file(
            PathBuf::from(config).join(format!("{app}.json")),
        ))
        .merge(Toml::file(
            PathBuf::from(config).join(format!("{app}.toml")),
        ))
        .merge(Yaml::file(
            PathBuf::from(config).join(format!("{app}.yaml")),
        ))
        .merge(Env::raw().split("_").only(&["database.url"]))
        .merge(Env::raw().split("__").ignore(&["database.url"]))
        .extract()
```

I do not see similar facilities using schematic. Could this be supported?

**Comment by milesj** [comment]
@IgnisDa Schematic only supports a single format type, but you can just chain multiple files.

```rust
ConfigLoader::<Test>::yaml()
	.file(file1)?
	.file(file2)?
	.file(file3)?
	.file(file4)?
	.load()?;
```

**Comment by IgnisDa** [comment]
What if I have data in multiple file types (i.e. json, yaml, toml etc)?

**Comment by milesj** [comment]
@IgnisDa You're out of luck. What's the use case?

**Comment by IgnisDa** [comment]
I am developing a self hosted application and I want users to be able to configure the instance via json, yaml and toml.

https://github.com/IgnisDa/ryot/blob/f4d3f13d8a78e6cc621e40352b633bba76687c84/apps/backend/src/config.rs#L299-L313

**Comment by milesj** [comment]
I looked into breaking up the parsers before, but could not satisfy serde lifetime requirements. https://github.com/moonrepo/schematic/tree/parsers
