### ISSUE TITLE
Serde attributes should be applied to nested children

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#30]
If I have a nested config:

```rs
#[derive(Config)]
pub struct ChildConfig {
    testing_field: String
}

#[derive(Config)]
#[config(rename_all = "snake_case")]
pub struct ParentConfig {
	#[setting(nested)]
	pub nested: ChildConfig
}
```

Schematic still expects `nested.testingField` instead of `nested.testing_field`. If I have a lot of nested children, it becomes very repetitive to add `#[config(rename_all = "snake_case")]` line to every child config.

**Comment by milesj** [comment]
This isn't possible because of how macros work.
