### ISSUE TITLE
Multiple env prefix for same struct

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#35]
I have a struct that is shared across two different fields. They require different env prefix, but schematic does not allow that yet.

```rs
#[derive(Debug, Config)]
#[config(env_prefix = "MOVIES_IMDB_")]
#[config(env_prefix = "SHOWS_IMDB_")] // <--- this is not allowed
pub struct ImdbConfig {
    pub url: String
}

#[derive(Debug, Config)]
pub struct MoviesConfig {
    #[setting(nested)]
    pub imdb: ImdbConfig
}

#[derive(Debug, Config)]
pub struct ShowsConfig {
    #[setting(nested)]
    pub imdb: ImdbConfig
}

#[derive(Debug, Config)]
pub struct AppConfig {
    #[setting(nested)]
    movies: MoviesConfig,

    #[setting(nested)]
    shows: ShowsConfig
}
```

If this is allowed somehow, then I will be able to use the same struct for `MOVIES_IMDB_URL` and `SHOWS_IMDB_URL` environment variables.

**Comment by IgnisDa** [comment]
Maybe `env_prefix` can be made a `Vec` instead?

**Comment by milesj** [comment]
Unfortunately I think you'll need 2 structs here. You can easily do this with a decl macro though, like `imdb_config!(MoviesImdbConfig)`. 

Even if we support `Vec`, the base `ImdbConfig` doesn't know which parent it's nested in, and which of the vars in the vec to read from.

**Comment by IgnisDa** [comment]
Thanks!
