### ISSUE TITLE
Incorrect environment variable names selected

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#37]
I have the following struct:

```rs
#[derive(Debug, Serialize, Deserialize, Clone, Config)]
#[config(rename_all = "snake_case", env_prefix = "FILE_STORAGE_")]
pub struct FileStorageConfig {
    pub s3_access_key_id: String,
    pub s3_bucket_name: String,
    #[setting(default = "us-east-1")]
    pub s3_region: String,
    pub s3_secret_access_key: String,
    pub s3_url: String,
}
```
I would expect the variable names to be `FILE_STORAGE_S3_ACCESS_KEY_ID`.

But here are the names being generated instead.

![image](https://github.com/moonrepo/schematic/assets/60938164/623adfee-3aab-4eb0-ae33-efcf2430577b)

**Comment by milesj** [comment]
@IgnisDa Looks like the casing converter lib is causing this. I suppose a to_uppercase will probably be enough.

**Comment by milesj** [comment]
Release 0.7.1

**Comment by IgnisDa** [comment]
@milesj Just a small bug. The schema generator creates the wrong variable name:
https://github.com/IgnisDa/ryot/blob/f74e24f92fec5f1b8f6e6f0bf55e3622c3296a54/libs/generated/src/config/backend/schema.ts#L59C1-L71C2
Maybe the same problem as above?
