### ISSUE TITLE
[FEAT] Display default value for schema generator

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#51]
It would be great if the default value for the typescript generator is shown:
```rs
#[derive(Debug, Serialize, Deserialize, Clone, Config)]
#[config(rename_all = "snake_case", env_prefix = "USERS_")]
pub struct UsersConfig {
    /// Whether users will be allowed to change their username in their profile settings.
    #[setting(default = true)]
    pub allow_changing_username: bool,
}
```
This generates:
```ts
export interface UsersConfig {
	// Whether users will be allowed to change their username in their profile settings.
	allow_changing_username: boolean;
}
```
I think this would be better:
```ts
export interface UsersConfig {
	// Whether users will be allowed to change their username in their profile settings. Default: true
	allow_changing_username: boolean;
}
```

**Comment by IgnisDa** [comment]
Preferably can be enabled via an option in `TypeScriptRenderer`

**Comment by milesj** [comment]
Added using `@default`.

**Comment by IgnisDa** [comment]
@milesj Thanks! Works well.

What values will have their default rendered? It looks to be random. 

Rendered: https://github.com/IgnisDa/ryot/blob/c2be439e2842449f43e27cd5f2efd8fe4be12157/libs/generated/src/config/backend/schema.ts#L32
Config: https://github.com/IgnisDa/ryot/blob/c2be439e2842449f43e27cd5f2efd8fe4be12157/apps/backend/src/config.rs#L89

**Comment by IgnisDa** [comment]
Or maybe its a bug since defaults for enums are not being rendered.

**Comment by milesj** [comment]
@IgnisDa Only primitives marked with `#[setting(default)]` are supported. And also only `Config`, not `ConfigEnum`.

**Comment by IgnisDa** [comment]
What about primitives which have default set to a function? https://github.com/IgnisDa/ryot/blob/c2be439e2842449f43e27cd5f2efd8fe4be12157/apps/backend/src/config.rs#L165

**Comment by milesj** [comment]
@IgnisDa Yeah that's not supported currently, since theoretically that value could keep changing.
