### ISSUE TITLE
[FEAT] Toml schema renderer

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#56]
The current options for rendering a schema are json and typescript. However the schema generated for json is too verbose and the one for typescript is too disconnected. Instead I'd recommend a toml renderer. Here is a good example of a config scheme: https://github.com/teamhanko/hanko/blob/main/backend/docs/Config.md

**Comment by IgnisDa** [comment]
Yep just exactly what the typescript renderer does but render it in toml format.

**Comment by IgnisDa** [comment]
Hey @milesj any updates on this?

**Comment by milesj** [comment]
I don't have time right now to look into it.

You can try doing it yourself by implementing a renderer: https://docs.rs/schematic/latest/schematic/schema/trait.SchemaRenderer.html

**Comment by milesj** [comment]
Gonna keep this open since I have some ideas for this.

**Comment by milesj** [comment]
Got this mostly working https://github.com/moonrepo/schematic/pull/86

Default values are complicated though.
