### ISSUE TITLE
Support `url::Url` instead of `schematic::validate::url` on `String`

### ISSUE THREAD

**Issue by Dessix** [moonrepo/schematic#59]
Currently, embedding a `Url` as a field results in a lack of `Schematic` implementations for `Url`, despite enabling the `valid_url` feature and enabling the JsonSchema `schemars/url` dependency feature.
Perhaps it'd be viable to support `Schematic` for any type which implements `schemars`'s `JsonSchema`?

**Comment by milesj** [comment]
The `valid_url` only enables validation rules from `garde` at the moment. You would need to implement `Schematic` manually for the time being. Should be as simple as:

```rust
impl Schematic for Url {
  pub generate_schema() -> SchemaType {
    SchemaType::string()
  }
}
```

**Comment by Dessix** [comment]
As URL isn't from my crate, [the orphan rule comes into play](https://serde.rs/remote-derive.html). `schemars` allows [derivation for external types](https://graham.cool/schemars/examples/5-remote_derive/) (if marked up on all uses of the target) for this sort of thing, but ... Well, very few `serde` or `schemars` properties are currently supported for passthrough by Schematic, or I wouldn't have this issue in the first place.

**Comment by milesj** [comment]
You're right, forgot about that. I'll add it today (I also need it, hah).
