### ISSUE TITLE
how to deal with float type?

### ISSUE THREAD

**Issue by ash0080** [moonrepo/schematic#65]
For now, it says The trait bound `f32: std::cmp::Eq` is not satisfied
should I use a safe float crate?

**Comment by milesj** [comment]
@ash0080 Oversight on my part. I think I can simply remove `Eq` since it already has `PartialEq`.

**Comment by ash0080** [comment]
> @ash0080 Oversight on my part. I think I can simply remove `Eq` since it already has `PartialEq`.

That's fantastic, thank you!
