### ISSUE TITLE
[Feature] Allow skipping fields completely

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#73]
I have a field in my struct that I want should be completely ignored by `schematic::Schematic` derive macro. I tried `#[serde(skip)]` as suggested in the readme but it does not work.

**Comment by milesj** [comment]
Hrmm, skipped marks it as "hidden" for JSON schema. Not sure what's a better approach.

**Comment by IgnisDa** [comment]
No I want schematic to ignore it altogether. The reason is that the field I want to "hide" has a type that is too complex for schematic to represent (i.e, the struct does not have `schematic::Schematic` derive on it).

```rs
#[derive(Schematic)]
struct A {
 a: String,
 b: ComplexType
}

// #[derive(Schematic)]
struct ComplexType {
 // fields that schematic does not support
}
```

**Comment by milesj** [comment]
@IgnisDa https://github.com/moonrepo/schematic/pull/74

**Comment by IgnisDa** [comment]
@milesj it works perffectly
