### ISSUE TITLE
`#[schematic(rename = "...")]` does not work

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#76]
The typescript renderer still takes the name of the `struct`.

**Comment by milesj** [comment]
@IgnisDa Is this on the container or on the field?

**Comment by IgnisDa** [comment]
On the container. (https://github.com/IgnisDa/ryot/blob/73d057578e4372989da1762cf5dfd0677d1dc9dd/apps/backend/src/entities/workout.rs#L21)

**Comment by milesj** [comment]
@IgnisDa At least in the `Config` case, this just sets `#[serde(rename)]`. Do you expect the same serde treatment here or another approach?

**Comment by milesj** [comment]
Actually, I don't think this would. With `Config`, we create a whole new struct, the partial struct, which we control.

With `Schematic`, we don't create anything new, so we can't inject `#[serde]` attributes. You would just need to use `#[serde]` directly.

**Comment by IgnisDa** [comment]
So you `serde(rename)` work?

**Comment by milesj** [comment]
Yeah it would.

But I guess a follow-up question. Are you trying to rename the "name" in like the JSON schema output? Or serde output? etc.

**Comment by IgnisDa** [comment]
In the typescript output.

**Comment by IgnisDa** [comment]
I just checked. `serde(rename = "...")` does not do anything at all.

**Comment by milesj** [comment]
Ok let me double check this.

**Comment by milesj** [comment]
Ok think I got it, try the next version.

**Comment by IgnisDa** [comment]
Yep it works now!
