### ISSUE TITLE
[BUG] `Json` template renderer does not work

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#87]
I am trying to render the following type: https://github.com/IgnisDa/ryot/blob/c790c07c4d64782fda94328e4d9ff57334d1c4c7/apps/backend/src/models.rs#L120.
```rs
   let mut generator = SchemaGenerator::default();
        generator.add::<CompleteExport>();
        generator
            .generate(
                base_dir.join("export-schema.json"),
                TemplateRenderer::new_format(Format::Json),
            )
            .unwrap();
    }
```

Here is what the rendered type is: 
```json
{
  // Data about user's measurements.
  "measurements": [],

  // Data about user's media.
  "media": [],

  // Data about user's people.
  "people": [],

  // Data about user's workouts.
  "workouts": [],
}
```

That is, the types are not rendered recursively.

**Comment by milesj** [comment]
@IgnisDa Can you add an example of what you want? Since there's "no data" for the array, it's basically empty and has nothing to render. I can maybe add an option that forces it to render like 1 item that matches the struct.

**Comment by milesj** [comment]
@IgnisDa Try this: https://moonrepo.github.io/schematic/schema/generator/template.html#field-expansion

**Comment by IgnisDa** [comment]
@milesj this works for my use case. Thanks. Can be closed.

**Comment by milesj** [comment]
Sweet
