### ISSUE TITLE
[BUG] Comments not rendered correctly

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#89]
I have the following comment: (https://github.com/IgnisDa/ryot/blob/540adc55f5d6c7f26e36fbdd402a74f058bd4979/libs/config/src/lib.rs#L177)
```rs
    /// The client ID issues by Twitch. **Required** to enable video games
    /// tracking. [More information](/docs/guides/video-games.md)
```

And it is rendered like this: (https://github.com/IgnisDa/ryot/blob/540adc55f5d6c7f26e36fbdd402a74f058bd4979/docs/includes/backend-config-schema.yaml#L246)
```yaml

    # The client ID issues by Twitch. **Required*to enable video games
    # tracking. [More information](/docs/guides/video-games.md)
```

(The `**Required**` is botched up).

**Comment by milesj** [comment]
Fixed
