### ISSUE TITLE
[BUG] `envvar` not being rendered for fields which do not have doc comment

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#90]
In this, (https://github.com/IgnisDa/ryot/blob/540adc55f5d6c7f26e36fbdd402a74f058bd4979/libs/config/src/lib.rs#L253)

```rs
#[derive(Debug, Serialize, Deserialize, Clone, Config)]
#[config(rename_all = "snake_case", env_prefix = "FRONTEND_UMAMI_")]
pub struct FrontendUmamiConfig {
    /// For example: https://umami.is/script.js
    pub script_url: String,
    pub website_id: String,
    pub domains: String,
}
```

The `website_id` does not have a comment, yet I expect the rendered documentation to contain the `@envvar` property. 

(You can see the rendered schema here: https://ignisda.github.io/ryot/configuration.html#all-parameters.)

**Comment by milesj** [comment]
Fixed
