### ISSUE TITLE
Unspecified environment variable ends up as an empty string

### ISSUE THREAD

**Issue by jfly** [moonrepo/schematic#99]
We're trying to use schematic like this:

```rust
use schematic::ConfigLoader;

#[derive(Debug, schematic::Config)]
struct Config {
    #[setting(env = "EXAMPLE_VAR")]
    EXAMPLE_VAR: String,
}

fn main() {
    let config: Config = ConfigLoader::new()
        .load()
        .context("loading configuration from environment").unwrap()
        .config;
    dbg!(config);
}
```

And if we run this, we get something like:

```
[.../src/main.rs:33] config = Config {
    EXAMPLE_VAR: "",
}
```

when we'd really expect to get an error about `EXAMPLE_VAR` not being specified.

**Comment by milesj** [comment]
@jfly Env vars are always optional, but you do have a few options here:

- Add a custom `parse_env` that errors if the env var is missing/empty: https://moonrepo.github.io/schematic/config/struct/env.html#parse-function
- Try using the `not_empty` validator: https://docs.rs/schematic/latest/schematic/validate/fn.not_empty.html

**Comment by jfly** [comment]
Thanks, @milesj. A couple of questions:

> Env vars are always optional

Sorry, I'm having trouble understanding this. I know I mentioned environment variables in the title, but in my mind, this isn't a question of whether an env var is required or optional, it's about a config setting that the user is required to specify. In the above example, it's the this rust struct attribute `Config.EXAMPLE_VAR` that is required (it's a `String`, not an `Option<String>`). I know schematic can handle loading config from multiple places, but regardless of how many places we're loading the config from, this feels to me like a situation where the user really should be expected give us a value somehow.

> Add a custom parse_env ...[or]... Try using the not_empty validator

We can give that a shot, but do you happen to know if we'll be able to distinguish between missing and truly present, but empty string? For missing, we'd like the user to receive an error, but if they set it to empty string, that's ok.

**Comment by milesj** [comment]
@jfly Yeah so the struct that derives `Config` is the "final state", after all partials have been loaded. If a field is missing in the partial, it gets filled with `Default`. So in this final config, a non-option setting doesn't mean that it's required, just that it would always have a value, even if empty/default.

You would need to use validation to handle this. We have a `#[setting(required)]` attribute, but that's only for `Option`s.

**Comment by mightyiam** [comment]
This design, where env vars are always optional... Why?

**Comment by milesj** [comment]
This design is primarily for config files, and ease of use on the Rust side. Environment variables are secondary, as they are used to populate a value and override those found in the config file.

**Comment by mightyiam** [comment]
Could we consider promoting env to a first class source of config, instead?

That would support the use case of an app that takes config only via env.

**Comment by milesj** [comment]
You could do that by implementing your own `parse_env` or `validator` functions.

**Comment by mightyiam** [comment]
I guess you have your priorities. Thanks anyway.

**Comment by milesj** [comment]
If it was built into core, it would be one of those approaches anyways.

**Comment by milesj** [comment]
Closing as there's nothing actionable.

**Comment by milesj** [comment]
Refer to https://github.com/moonrepo/schematic/pull/171#issuecomment-3140736725
